### ISSUE TITLE
How to nest menus?

### ISSUE THREAD

**Issue by richardrobberse** [stackbithq/gatsby-plugin-menus#8]
Hi guys, I've followed the readme but it's not clear how to nest menus.
Could you please elaborate on the frontmatter I have to use in order to nest a menu?

Thanks in advance!

**Comment by smnh** [comment]
Hi @richardrobberse,

To create parent-child relationships between menus, you need add `identifier` property to a menu item that you want to use as a parent menu. Then use the value of that `identifier` as the menu name of child menu item.

```yaml
---
title: Foo
menus:
  main: 
    identifier: sub_menu # identifier for this menu item to be used by child menu item
    title: Go to Foo
    weight: 1
---
```

```yaml
---
title: Bar
menus:
  sub_menu: # the identifier of the parent menu
    title: Go to Bar
    weight: 1
---
```
